/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PortfolioImport } from './routes/portfolio'
import { Route as LoginImport } from './routes/login'
import { Route as DesignReviewImport } from './routes/design-review'
import { Route as CasesImport } from './routes/cases'
import { Route as IndexImport } from './routes/index'
import { Route as DomainDomainImport } from './routes/domain/$domain'

// Create/Update Routes

const PortfolioRoute = PortfolioImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DesignReviewRoute = DesignReviewImport.update({
  id: '/design-review',
  path: '/design-review',
  getParentRoute: () => rootRoute,
} as any)

const CasesRoute = CasesImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DomainDomainRoute = DomainDomainImport.update({
  id: '/domain/$domain',
  path: '/domain/$domain',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesImport
      parentRoute: typeof rootRoute
    }
    '/design-review': {
      id: '/design-review'
      path: '/design-review'
      fullPath: '/design-review'
      preLoaderRoute: typeof DesignReviewImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioImport
      parentRoute: typeof rootRoute
    }
    '/domain/$domain': {
      id: '/domain/$domain'
      path: '/domain/$domain'
      fullPath: '/domain/$domain'
      preLoaderRoute: typeof DomainDomainImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/design-review': typeof DesignReviewRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/domain/$domain': typeof DomainDomainRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/design-review': typeof DesignReviewRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/domain/$domain': typeof DomainDomainRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/design-review': typeof DesignReviewRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/domain/$domain': typeof DomainDomainRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/design-review'
    | '/login'
    | '/portfolio'
    | '/domain/$domain'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cases'
    | '/design-review'
    | '/login'
    | '/portfolio'
    | '/domain/$domain'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/design-review'
    | '/login'
    | '/portfolio'
    | '/domain/$domain'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRoute
  DesignReviewRoute: typeof DesignReviewRoute
  LoginRoute: typeof LoginRoute
  PortfolioRoute: typeof PortfolioRoute
  DomainDomainRoute: typeof DomainDomainRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRoute,
  DesignReviewRoute: DesignReviewRoute,
  LoginRoute: LoginRoute,
  PortfolioRoute: PortfolioRoute,
  DomainDomainRoute: DomainDomainRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cases",
        "/design-review",
        "/login",
        "/portfolio",
        "/domain/$domain"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/cases": {
      "filePath": "cases.tsx"
    },
    "/design-review": {
      "filePath": "design-review.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/portfolio": {
      "filePath": "portfolio.tsx"
    },
    "/domain/$domain": {
      "filePath": "domain/$domain.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
