/**
 * Finding Repository
 *
 * Manages persisted DNS and mail findings linked to snapshots.
 * Findings are generated by the rules engine and stored for auditing
 * and historical comparison.
 */

import { and, eq } from 'drizzle-orm';
import type { IDatabaseAdapter } from '../database/simple-adapter.js';
import { type Finding, findings, type NewFinding } from '../schema/index.js';

export class FindingRepository {
  constructor(private db: IDatabaseAdapter) {}

  /**
   * Find a finding by ID
   */
  async findById(id: string): Promise<Finding | null> {
    const result = await this.db.selectOne(findings, eq(findings.id, id));
    return result || null;
  }

  /**
   * Find all findings for a snapshot
   */
  async findBySnapshotId(snapshotId: string): Promise<Finding[]> {
    return this.db.selectWhere(findings, eq(findings.snapshotId, snapshotId));
  }

  /**
   * Find findings for a snapshot filtered by severity
   */
  async findBySnapshotIdAndSeverity(snapshotId: string, severities: string[]): Promise<Finding[]> {
    const allFindings = await this.findBySnapshotId(snapshotId);
    return allFindings.filter((f) => severities.includes(f.severity));
  }

  /**
   * Find findings by rule ID
   */
  async findByRuleId(ruleId: string, snapshotId?: string): Promise<Finding[]> {
    const allFindings = snapshotId
      ? await this.findBySnapshotId(snapshotId)
      : await this.db.select(findings);
    return allFindings.filter((f) => f.ruleId === ruleId);
  }

  /**
   * Find findings by type (e.g., 'dns.authoritative-failure', 'mail.spf-missing')
   */
  async findByType(type: string, snapshotId?: string): Promise<Finding[]> {
    const allFindings = snapshotId
      ? await this.findBySnapshotId(snapshotId)
      : await this.db.select(findings);
    return allFindings.filter((f) => f.type === type);
  }

  /**
   * Create a new finding
   */
  async create(data: NewFinding): Promise<Finding> {
    return this.db.insert(findings, data);
  }

  /**
   * Create multiple findings
   */
  async createMany(data: NewFinding[]): Promise<Finding[]> {
    if (data.length === 0) return [];
    return this.db.insertMany(findings, data);
  }

  /**
   * Mark a finding as acknowledged
   */
  async markAcknowledged(
    id: string,
    snapshotId: string,
    acknowledgedBy: string
  ): Promise<Finding | null> {
    const predicate = and(eq(findings.id, id), eq(findings.snapshotId, snapshotId));
    if (!predicate) return null;
    return (
      (await this.db.updateOne(
        findings,
        {
          acknowledgedAt: new Date(),
          acknowledgedBy,
        },
        predicate
      )) ?? null
    );
  }

  /**
   * Mark a finding as a false positive
   */
  async markFalsePositive(
    id: string,
    snapshotId: string,
    acknowledgedBy: string
  ): Promise<Finding | null> {
    const predicate = and(eq(findings.id, id), eq(findings.snapshotId, snapshotId));
    if (!predicate) return null;
    return (
      (await this.db.updateOne(
        findings,
        {
          falsePositive: true,
          acknowledgedAt: new Date(),
          acknowledgedBy,
        },
        predicate
      )) ?? null
    );
  }

  /**
   * Delete all findings for a snapshot
   * Used when re-evaluating a snapshot with a new ruleset
   */
  async deleteBySnapshotId(snapshotId: string): Promise<number> {
    const existingFindings = await this.findBySnapshotId(snapshotId);
    if (existingFindings.length === 0) return 0;

    // Delete all findings for this snapshot
    await this.db.delete(findings, eq(findings.snapshotId, snapshotId));
    return existingFindings.length;
  }

  /**
   * Count findings for a snapshot by severity
   */
  async countBySeverity(snapshotId: string): Promise<Record<string, number>> {
    const allFindings = await this.findBySnapshotId(snapshotId);
    const counts: Record<string, number> = {
      critical: 0,
      high: 0,
      medium: 0,
      low: 0,
      info: 0,
    };

    for (const finding of allFindings) {
      counts[finding.severity] = (counts[finding.severity] || 0) + 1;
    }

    return counts;
  }

  /**
   * Check if a snapshot has any findings
   */
  async hasFindings(snapshotId: string): Promise<boolean> {
    const result = await this.findBySnapshotId(snapshotId);
    return result.length > 0;
  }

  /**
   * Find findings for a snapshot evaluated with a specific ruleset version.
   * Used for idempotent re-evaluation - returns existing findings if they match the ruleset.
   */
  async findBySnapshotIdAndRulesetVersionId(
    snapshotId: string,
    rulesetVersionId: string
  ): Promise<Finding[]> {
    const allFindings = await this.findBySnapshotId(snapshotId);
    return allFindings.filter((f) => f.rulesetVersionId === rulesetVersionId);
  }

  /**
   * Check if findings exist for a specific (snapshotId, rulesetVersionId) combination.
   * Used to determine if re-evaluation is needed.
   */
  async hasFindingsForRulesetVersion(
    snapshotId: string,
    rulesetVersionId: string
  ): Promise<boolean> {
    const matchingFindings = await this.findBySnapshotIdAndRulesetVersionId(
      snapshotId,
      rulesetVersionId
    );
    return matchingFindings.length > 0;
  }

  /**
   * Delete findings for a specific (snapshotId, rulesetVersionId) combination.
   * Used when explicitly re-evaluating with the same ruleset version.
   */
  async deleteBySnapshotIdAndRulesetVersionId(
    snapshotId: string,
    rulesetVersionId: string
  ): Promise<number> {
    const matchingFindings = await this.findBySnapshotIdAndRulesetVersionId(
      snapshotId,
      rulesetVersionId
    );
    if (matchingFindings.length === 0) return 0;

    // Delete matching findings by ID
    for (const finding of matchingFindings) {
      await this.db.delete(findings, eq(findings.id, finding.id));
    }
    return matchingFindings.length;
  }
}
